### ISSUE TITLE
ImportError after upgrading to Django 3.0 (not supported)

### ISSUE THREAD

**Issue by jar3b** [SectorLabs/django-localized-fields#73]
`ImportError: cannot import name 'six' from 'django.utils'` was thrown after upgrading to  Django 3.0.

Trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/localized_fields/apps.py", line 7, in <module>
    from .fields import LocalizedField
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/localized_fields/fields/__init__.py", line 1, in <module>
    from .field import LocalizedField
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/localized_fields/fields/field.py", line 12, in <module>
    from ..descriptor import LocalizedValueDescriptor
  File "/home/jar3b/work/test/venv/lib/python3.7/site-packages/localized_fields/descriptor.py", line 2, in <module>
    from django.utils import six, translation
ImportError: cannot import name 'six' from 'django.utils' (/home/jar3b/work/test/venv/lib/python3.7/site-packages/django/utils/__init__.py)
```

Reason is because version 5.4.1 (and beta-6 from `master`) doesn't support one of django 3.0 changes - `django.utils.six` has been removed. Solution is to drop support for `six` due to package only supports python3.7 and above.

**Comment by Photonios** [comment]
Thank you for the contribution! I've merged your fixes and released a new beta on PyPi.

https://pypi.org/project/django-localized-fields/6.0b2/

The package should now work with Django 3.0. Please re-open this issue if you encounter any further issues.
